apiVersion: skaffold/v2beta26
kind: Config
build:
  artifacts:
  - image: portfolio-reader-svc
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      k8s/base/portfolio-reader-svc.yaml
