apiVersion: apps/v1
kind: Deployment
metadata:
  name: market-reader-svc
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: market-reader-svc
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
