apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: consistency-manager-svc
build:
  artifacts:
  - image: consistency-manager-svc
    docker:
      dockerfile: Dockerfile
deploy:
  kustomize:
    paths:
    - k8s/overlays/development