apiVersion: apps/v1
kind: Deployment
metadata:
  name: withdraw-svc
  labels:
    app: withdraw-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: withdraw-svc
  template:
    metadata:
      labels:
        app: withdraw-svc
    spec:
      containers:
      - name: withdraw-svc
        image: withdraw-svc
        ports:
        - containerPort: 8080
        env:
        - name: USER_PORTFOLIO_DB_URI
          value: "postgresql://portfolio-admin:portfolio-pwd@user-portfolio-db:5432/user-portfolio-db"
        - name: USER_TIER_AGENT_URI
          value: "http://user-tier-agent:8080"
        - name: PORT
          value: "8080"
        - name: REQUEST_TIMEOUT
          value: "30"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: withdraw-svc
  labels:
    app: withdraw-svc
spec:
  selector:
    app: withdraw-svc
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
