# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: Service
metadata:
  labels:
    application: bank-of-anthos
    environment: development
    team: assets
    tier: backend
  name: bank-asset-agent
spec:
  ports:
    - name: grpc
      port: 8080
      targetPort: 8080
  selector:
    app: bank-asset-agent
    application: bank-of-anthos
    environment: development
    team: assets
    tier: backend
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    application: bank-of-anthos
    environment: development
    team: assets
    tier: backend
  name: bank-asset-agent
spec:
  selector:
    matchLabels:
      app: bank-asset-agent
      application: bank-of-anthos
      environment: development
      team: assets
      tier: backend
  template:
    metadata:
      labels:
        app: bank-asset-agent
        application: bank-of-anthos
        environment: development
        team: assets
        tier: backend
    spec:
      serviceAccountName: bank-of-anthos
      containers:
        - name: bank-asset-agent
          image: bank-asset-agent
          ports:
            - containerPort: 8080
          env:
            - name: VERSION
              value: "dev"
            - name: PORT
              value: "8080"
            - name: ENABLE_TRACING
              value: "true"
            - name: ENABLE_METRICS
              value: "true"
            - name: MARKET_READER_URL
              value: "http://market-reader-svc:8080"
            - name: RULE_CHECKER_URL
              value: "http://rule-checker-svc:8080"
            - name: EXECUTE_ORDER_URL
              value: "http://execute-order-svc:8080"
            - name: QUEUE_SVC_URL
              value: "http://user-request-queue-svc:8080"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/etc/credentials/credentials.json"
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: gemini-api-key
                  key: api-key
          envFrom:
            - configMapRef:
                name: environment-config
            - configMapRef:
                name: demo-data-config
            - configMapRef:
                name: assets-db-config
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: credentials
              mountPath: /etc/credentials
              readOnly: true
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 10
          startupProbe:
            tcpSocket:
              port: 8080
            failureThreshold: 30
            periodSeconds: 10
      volumes:
        - name: credentials
          secret:
            secretName: bank-asset-agent-credentials