apiVersion: v1
kind: Service
metadata:
  name: investment-manager-svc
  labels:
    app: investment-manager-svc
    application: bank-of-anthos
    environment: development
    team: investment
    tier: service
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: investment-manager-svc
    application: bank-of-anthos
    environment: development
    team: investment
    tier: service
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: investment-manager-svc
  labels:
    app: investment-manager-svc
    application: bank-of-anthos
    environment: development
    team: investment
    tier: service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: investment-manager-svc
      application: bank-of-anthos
      environment: development
      team: investment
      tier: service
  template:
    metadata:
      labels:
        app: investment-manager-svc
        application: bank-of-anthos
        environment: development
        team: investment
        tier: service
    spec:
      containers:
        - name: investment-manager-svc
          image: gcr.io/ffd-gke10/investment-manager-svc:latest
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: PORT
              value: "8080"
            - name: PORTFOLIO_READER_URI
              value: "http://portfolio-reader-svc:8080"
            - name: INVEST_SVC_URI
              value: "http://invest-svc:8080"
            - name: WITHDRAW_SVC_URI
              value: "http://withdraw-svc:8080"
            - name: LEDGER_WRITER_URI
              value: "http://ledgerwriter:8080"
            - name: LOCAL_ROUTING_NUM
              valueFrom:
                configMapKeyRef:
                  name: environment-config
                  key: LOCAL_ROUTING_NUM
            - name: INVESTMENT_BANK_ACCOUNT
              value: "9999999999"
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: secret
            - name: JWT_ALGORITHM
              value: "HS256"
            - name: JWT_EXPIRATION_HOURS
              value: "24"
            - name: REQUEST_TIMEOUT
              value: "30"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
