apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - investment-manager-svc.yaml

commonLabels:
  application: bank-of-anthos
  team: investment
  tier: service

images:
  - name: investment-manager-svc
    newTag: latest
