apiVersion: apps/v1
kind: Deployment
metadata:
  name: consistency-manager-svc
  labels:
    app: consistency-manager-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consistency-manager-svc
  template:
    metadata:
      labels:
        app: consistency-manager-svc
    spec:
      containers:
      - name: consistency-manager-svc
        image: consistency-manager-svc
        ports:
        - containerPort: 8080
        env:
        - name: QUEUE_DB_URI
          value: "postgresql://queue-admin:queue-pwd@queue-db:5432/queue-db"
        - name: USER_PORTFOLIO_DB_URI
          value: "postgresql://portfolio-admin:portfolio-pwd@user-portfolio-db:5432/user-portfolio-db"
        - name: POLLING_INTERVAL
          value: "30"
        - name: PORT
          value: "8080"
        - name: TIER1
          value: "1000000.0"
        - name: TIER1_MV
          value: "1000000.0"
        - name: TIER2
          value: "2000000.0"
        - name: TIER2_MV
          value: "2000000.0"
        - name: TIER3
          value: "500000.0"
        - name: TIER3_MV
          value: "500000.0"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: consistency-manager-svc
  labels:
    app: consistency-manager-svc
spec:
  selector:
    app: consistency-manager-svc
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP