apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- execute-order-svc.yaml

commonLabels:
  app.kubernetes.io/name: execute-order-svc
  app.kubernetes.io/instance: execute-order-svc
  app.kubernetes.io/component: microservice
  app.kubernetes.io/part-of: bank-of-anthos

images:
- name: execute-order-svc
  newTag: latest
