apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-reader-svc
spec:
  template:
    spec:
      containers:
      - name: portfolio-reader-svc
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "100m"
