apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - investment-manager-svc.yaml

commonLabels:
  environment: development

images:
  - name: investment-manager-svc
    newTag: dev
