apiVersion: skaffold/v4beta7
kind: Config
build:
  artifacts:
  - image: invest-svc
    docker:
      dockerfile: Dockerfile
  local:
    push: false
deploy:
  kustomize:
    paths:
    - k8s/overlays/development
